version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "20:00"
      timezone: Australia/Melbourne
    open-pull-requests-limit: 5
    groups:
      development-tooling:
        dependency-type: development
        update-types:
          - minor
          - patch
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: "20:00"
      timezone: Australia/Melbourne
    open-pull-requests-limit: 3
